### ISSUE TITLE
README missing link / invalid reference to “About section of this page”

### ISSUE THREAD

**Issue by Kissaki** [OpenTermsArchive/dating-versions#1]
The README says

> You can find the documentation by following the link in the “About” section of this page.

What *About section* is that referring to?

**Comment by MattiSG** [comment]
Thanks @Kissaki for highlighting this ambiguity!

The “about” section on GitHub is the one below:

<img width="340" alt="Screen Shot 2022-11-01 at 14 18 25" src="https://user-images.githubusercontent.com/222463/199221594-913a3eb1-5f5f-44d4-9196-ac1e81b6f069.png">

I added the link that was missing just like you had reported in https://github.com/OpenTermsArchive/contrib-versions/issues/13.

I understand this indirection is not the most user-friendly. We made that choice so that our [repository template](https://github.com/OpenTermsArchive/template-versions/) applies to all cases, as editing the metadata of repositories is easier than modifying the README individually. Your reports might make us reconsider 😉

Would you see a clearer name than _About section_ in that context? 🙂

**Comment by Kissaki** [comment]
Apart from the discoverability of the reference, I would also consider that the README is in a git repository that will be cloned, so the reference should also remain valid outside of the GitHub interface of the repository.

Given that the link goes to the general ambanum/OpenTermsArchive/README anyway, it seems to me that it could be a part of the template!?

If not, instead of

> This repository is to be considered as a database only. You can find the documentation by following the link in the “About” section of this page.

it could either describe it abstractly

> This repository is to be considered as a database only. It is updated automatically from the service definitions in the declarations service declarations.

or more explicitly and general

> This repository is to be considered as a database only. For more information please refer to the general declarations and versions documentation.

> This repository is to be considered as a database only. For more information please refer to the general declarations and versions documentation linked to on the GitHub repository page.

**Comment by MattiSG** [comment]
Thank you very much for these useful suggestions and remarks. I agree with you that more details on how this is generated are needed, the current description is too focused on reading and misses elements on how to edit. A CONTRIBUTING file could also be useful, so that potential contributors can be redirected to the declarations instead of opening issues in an inadequate repository.

We wanted to preserve the ability to move the documentation around as it evolved (it already changed location twice). As we consolidate it, we might reach a stage where we can indeed make a direct link.
